### ISSUE TITLE
16.13.1分支，npm install 后， npm start启动时报错

### ISSUE THREAD

**Issue by neroneroffy** [Terry-Su/debug-react-source-code#1]
报错信息如下
```
E:\Code\debug-react-source-code>npm start

> debug-react-source-code@1.0.0 start E:\Code\debug-react-source-code
> node index.js

E:\Code\debug-react-source-code\index.js:14
if (dirs.length === 0) { throw new Error('No React Source Code Directory Found!') }
                         ^

Error: No React Source Code Directory Found!
    at Object.<anonymous> (E:\Code\debug-react-source-code\index.js:14:32)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! debug-react-source-code@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the debug-react-source-code@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\haita\AppData\Roaming\npm-cache\_logs\2020-06-28T16_01_43_747Z-debug.log

```

**Comment by neroneroffy** [comment]
原因是分支没有切正确
